/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mw.gov.agriculture.assestmanager.forms;

import at.favre.lib.crypto.bcrypt.BCrypt;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mw.gov.agriculture.assestmanager.helpers.ComboBoxItem;
import mw.gov.agriculture.assestmanager.models.AssetsCount;
import mw.gov.agriculture.assestmanager.models.Institution;
import mw.gov.agriculture.assestmanager.models.LoginSummary;
import mw.gov.agriculture.assestmanager.models.Report;
import mw.gov.agriculture.assestmanager.models.SystemAdmin;
import mw.gov.agriculture.assestmanager.models.User;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ICT-MUBAS
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * setLabel2();
        setLabel1();
        setInstSummary();
        setLoginSummary();
     */
    
    
    SystemAdmin user;
    
    public AdminDashboard(SystemAdmin admin){
        this.user=admin;
        initComponents();
        setInstitutitonTable();
        setInstitutions();
        setUserCountLabel();
        setUsersTable();
        setInstSummary();
        setLoginSummary();
        setReportChart();
        setReducedBalanceCount();
        setInstitutionCountLabel();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
    }
    public void setDashboardPanel(){
        dashboardContainer.removeAll();
        dashboardContainer.add(dashStatistics);
        dashboardContainer.revalidate();
        dashboardContainer.repaint();
    }
    public void setUsersPanel(){
        dashboardContainer.removeAll();
        dashboardContainer.add(dashUsers);
        dashboardContainer.revalidate();
        dashboardContainer.repaint();
    }
    public void setReportsPanel(){
        dashboardContainer.removeAll();
        dashboardContainer.add(dashReports);
        dashboardContainer.revalidate();
        dashboardContainer.repaint();
    }
    public void setInstitutionPanel(){
        dashboardContainer.removeAll();
        dashboardContainer.add(dashInstitutions);
        dashboardContainer.revalidate();
        dashboardContainer.repaint();
    }
    public void setInstitutitonTable(){
        ArrayList<Institution>list=user.getInstitutions();
        if(list==null){
            System.out.println("Error");
        }else{
            DefaultTableModel model=new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Name");
            model.addColumn("Location");
            model.addColumn("Address");
            model.addColumn("Email");
            model.addColumn("Phone");
            model.addColumn("Description");
            model.addColumn("State");
            for(Institution inst: list){
                model.addRow(new Object[]{
                inst.getId(),
                inst.getName(),
                inst.getLocation(),
                inst.getAddress(),
                inst.getEmail(),
                inst.getPhone(),
                inst.getDescription(),
                inst.getState()
                });
            }
            inst_table.setModel(model);
        }
    }
    public void setUsersTable(){
         ArrayList<User>list=user.getUsers();
        if(list==null){
            System.out.println("Error");
        }else{
            DefaultTableModel model=new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("First Name");
            model.addColumn("Surname");
            model.addColumn("Email");
            model.addColumn("Role");
            model.addColumn("Institution");
            model.addColumn("State");
            
            
            for(User user: list){
                model.addRow(new Object[]{
                    user.getId(),
                    user.getFname(),
                    user.getLname(),
                    user.getEmail(),
                    user.getRole(),
                    user.getInstitution().getName(),
                    user.getState()
                });
            }
            users_table.setModel(model);
        }
    }
    public void setInstSummary(){
        ArrayList<AssetsCount> list=user.getInstByAssets();
        if(list==null){
            System.out.println("Error");
        }else{
            i1.setText(list.get(0).getName());
            i2.setText(list.get(1).getName());
            i3.setText(list.get(2).getName());
            i4.setText(list.get(3).getName());
            i5.setText(list.get(4).getName());
//            i1.setText(list.get(0).getName());

            v1.setText(Integer.toString(list.get(0).getCount()));            
            v2.setText(Integer.toString(list.get(1).getCount()));
            v3.setText(Integer.toString(list.get(2).getCount()));
            v4.setText(Integer.toString(list.get(3).getCount()));
            v5.setText(Integer.toString(list.get(4).getCount()));

        }
    }
    public void setLoginSummary(){
        ArrayList <LoginSummary> list=user.getLoginSummary();
        if(list==null){
            System.out.println("Error");
        }else{
            user1.setText(list.get(0).getUsername());            
            user2.setText(list.get(1).getUsername());
            user3.setText(list.get(2).getUsername());
            user4.setText(list.get(3).getUsername());
            user5.setText(list.get(4).getUsername());

            time1.setText(list.get(0).getTime());
            time2.setText(list.get(1).getTime());
            time3.setText(list.get(2).getTime());
            time4.setText(list.get(3).getTime());
            time5.setText(list.get(4).getTime());
        }
    }
    
    public void setReportChart(){
        ArrayList <Report> list=user.getReport();
        if(list==null){
            System.out.println("Error");
        }else{
            DefaultCategoryDataset dataset=new DefaultCategoryDataset();
           for (Report report : list) {
            // Assuming getScore(), getCategory(), and getDepartment() are appropriate getter methods
            dataset.addValue(report.getScore(), "Makawa", report.getDepartment());
        }
            JFreeChart chart = ChartFactory.createBarChart(
                    "Asset Distribution",
                    "Department",
                    "Asset Count",
                    dataset,
                    PlotOrientation.VERTICAL,
                    false,
                    false,
                    false
            );
            chart.setBackgroundPaint(Color.white);
            CategoryPlot plot = chart.getCategoryPlot();
            BarRenderer renderer = (BarRenderer) plot.getRenderer();
            renderer.setMaximumBarWidth(1);
            plot.setBackgroundPaint(Color.white);

            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(500, 400));
            statReportChart.setLayout(new BorderLayout());
            statReportChart.add(chartPanel, BorderLayout.CENTER);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backgroundPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        institution_btn = new javax.swing.JButton();
        users_btn = new javax.swing.JButton();
        reports_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        dashboard_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dashboardContainer = new javax.swing.JPanel();
        dashUsers = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        all_users = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();
        new_user = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        user_fname = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        user_sname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        user_email = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        user_save_btn = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        user_institution = new javax.swing.JComboBox();
        user_role = new javax.swing.JComboBox<>();
        user_password_field = new javax.swing.JPasswordField();
        dashInstitutions = new javax.swing.JPanel();
        instutionsPane = new javax.swing.JTabbedPane();
        all_institutions = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inst_table = new javax.swing.JTable();
        new_institutions = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inst_name = new javax.swing.JTextField();
        institution_save_btn = new javax.swing.JButton();
        inst_location = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        inst_email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inst_address = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        inst_phone = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        inst_description = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dashStatistics = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        statInstututions = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        inst_count = new javax.swing.JLabel();
        statUsers = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        sm_count = new javax.swing.JLabel();
        statSystemusage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        user3 = new javax.swing.JLabel();
        user4 = new javax.swing.JLabel();
        user5 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        statUsers1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        users_count1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        i1 = new javax.swing.JLabel();
        v1 = new javax.swing.JLabel();
        i2 = new javax.swing.JLabel();
        i4 = new javax.swing.JLabel();
        i5 = new javax.swing.JLabel();
        v5 = new javax.swing.JLabel();
        v3 = new javax.swing.JLabel();
        v2 = new javax.swing.JLabel();
        i3 = new javax.swing.JLabel();
        v4 = new javax.swing.JLabel();
        dashReports = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        statSystemusage1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        barchart_panel = new javax.swing.JPanel();
        statSystemusage2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        chart2 = new javax.swing.JPanel();
        statReportChart = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("admindashboard"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        backgroundPanel.setBackground(new java.awt.Color(9, 171, 187));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manager");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Asset");

        institution_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        institution_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/group.png"))); // NOI18N
        institution_btn.setText("Institutions");
        institution_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        institution_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institution_btnActionPerformed(evt);
            }
        });

        users_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        users_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/users.png"))); // NOI18N
        users_btn.setText("Users");
        users_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        users_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                users_btnActionPerformed(evt);
            }
        });

        reports_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        reports_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reports.png"))); // NOI18N
        reports_btn.setText("Reports");
        reports_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reports_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reports_btnActionPerformed(evt);
            }
        });

        logout_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.setActionCommand("");
        logout_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        dashboard_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dashboard_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home (3).png"))); // NOI18N
        dashboard_btn.setText("Dashboard");
        dashboard_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_btnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assetmanager/assets/assetlog3.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(reports_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(users_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(institution_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dashboard_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159)
                .addComponent(dashboard_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(institution_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(users_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reports_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(logout_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        dashboardContainer.setBackground(new java.awt.Color(255, 255, 255));
        dashboardContainer.setLayout(new java.awt.CardLayout());

        dashUsers.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setText("Users");

        jTabbedPane1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        all_users.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        users_table.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        users_table.setShowGrid(true);
        users_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                users_tableMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(users_table);

        javax.swing.GroupLayout all_usersLayout = new javax.swing.GroupLayout(all_users);
        all_users.setLayout(all_usersLayout);
        all_usersLayout.setHorizontalGroup(
            all_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(616, Short.MAX_VALUE))
        );
        all_usersLayout.setVerticalGroup(
            all_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_usersLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("All Users", all_users);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Fname");

        user_fname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Sname");

        user_sname.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("Email");

        user_email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Default Password");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel21.setText("Institution");

        user_save_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        user_save_btn.setForeground(new java.awt.Color(9, 171, 187));
        user_save_btn.setText("Save");
        user_save_btn.setActionCommand("");
        user_save_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(9, 171, 187)));
        user_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_save_btnActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel22.setText("Role");

        user_institution.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        user_role.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        user_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sysadmin", "instadmin" }));

        javax.swing.GroupLayout new_userLayout = new javax.swing.GroupLayout(new_user);
        new_user.setLayout(new_userLayout);
        new_userLayout.setHorizontalGroup(
            new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_userLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(new_userLayout.createSequentialGroup()
                        .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_sname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_fname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, new_userLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(new_userLayout.createSequentialGroup()
                        .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(new_userLayout.createSequentialGroup()
                                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(user_institution, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_role, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(user_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(140, 140, 140))
                            .addComponent(user_password_field))))
                .addContainerGap(722, Short.MAX_VALUE))
        );
        new_userLayout.setVerticalGroup(
            new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_userLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_sname, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(user_email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(user_password_field))
                .addGap(19, 19, 19)
                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_institution, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_role, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(user_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("New User", new_user);

        javax.swing.GroupLayout dashUsersLayout = new javax.swing.GroupLayout(dashUsers);
        dashUsers.setLayout(dashUsersLayout);
        dashUsersLayout.setHorizontalGroup(
            dashUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashUsersLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(dashUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashUsersLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        dashUsersLayout.setVerticalGroup(
            dashUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashUsersLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        dashboardContainer.add(dashUsers, "card3");

        dashInstitutions.setBackground(new java.awt.Color(255, 255, 255));

        instutionsPane.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        all_institutions.setBackground(new java.awt.Color(255, 255, 255));
        all_institutions.setForeground(new java.awt.Color(153, 153, 153));
        all_institutions.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        inst_table.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inst_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inst_tableMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(inst_table);

        javax.swing.GroupLayout all_institutionsLayout = new javax.swing.GroupLayout(all_institutions);
        all_institutions.setLayout(all_institutionsLayout);
        all_institutionsLayout.setHorizontalGroup(
            all_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_institutionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE)
                .addContainerGap())
        );
        all_institutionsLayout.setVerticalGroup(
            all_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(all_institutionsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        instutionsPane.addTab("All Institutions ", all_institutions);

        new_institutions.setBackground(new java.awt.Color(255, 255, 255));
        new_institutions.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Name");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Location");

        inst_name.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        institution_save_btn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        institution_save_btn.setForeground(new java.awt.Color(9, 171, 187));
        institution_save_btn.setText("Save");
        institution_save_btn.setActionCommand("");
        institution_save_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(9, 171, 187)));
        institution_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                institution_save_btnActionPerformed(evt);
            }
        });

        inst_location.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Email");

        inst_email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Address");

        inst_address.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Phone");

        inst_phone.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        inst_description.setColumns(20);
        inst_description.setRows(5);
        jScrollPane2.setViewportView(inst_description);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Description");

        javax.swing.GroupLayout new_institutionsLayout = new javax.swing.GroupLayout(new_institutions);
        new_institutions.setLayout(new_institutionsLayout);
        new_institutionsLayout.setHorizontalGroup(
            new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_institutionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(new_institutionsLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(institution_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(new_institutionsLayout.createSequentialGroup()
                        .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inst_location, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inst_name, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inst_email, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inst_address, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inst_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(818, Short.MAX_VALUE))
        );
        new_institutionsLayout.setVerticalGroup(
            new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(new_institutionsLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_name, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_location, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_address, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inst_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(new_institutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(institution_save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        instutionsPane.addTab("New Institution", new_institutions);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setText("Institutions");

        javax.swing.GroupLayout dashInstitutionsLayout = new javax.swing.GroupLayout(dashInstitutions);
        dashInstitutions.setLayout(dashInstitutionsLayout);
        dashInstitutionsLayout.setHorizontalGroup(
            dashInstitutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashInstitutionsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(dashInstitutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(instutionsPane)
                    .addGroup(dashInstitutionsLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dashInstitutionsLayout.setVerticalGroup(
            dashInstitutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashInstitutionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instutionsPane)
                .addGap(108, 108, 108))
        );

        dashboardContainer.add(dashInstitutions, "card4");

        dashStatistics.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Dashboard");

        statInstututions.setBackground(new java.awt.Color(255, 255, 255));
        statInstututions.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Institutions");

        inst_count.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        inst_count.setText("0");

        javax.swing.GroupLayout statInstututionsLayout = new javax.swing.GroupLayout(statInstututions);
        statInstututions.setLayout(statInstututionsLayout);
        statInstututionsLayout.setHorizontalGroup(
            statInstututionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statInstututionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statInstututionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inst_count, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        statInstututionsLayout.setVerticalGroup(
            statInstututionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statInstututionsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(inst_count, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        statUsers.setBackground(new java.awt.Color(255, 255, 255));
        statUsers.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Straight Method Assets");

        sm_count.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        sm_count.setText("0");

        javax.swing.GroupLayout statUsersLayout = new javax.swing.GroupLayout(statUsers);
        statUsers.setLayout(statUsersLayout);
        statUsersLayout.setHorizontalGroup(
            statUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sm_count, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        statUsersLayout.setVerticalGroup(
            statUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statUsersLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(sm_count, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        statSystemusage.setBackground(new java.awt.Color(255, 255, 255));
        statSystemusage.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Active Users");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("Last Seen");

        user1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user1.setText("martha@gmail.com");

        time1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        time1.setText("24-12-12 17:53");

        user2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user2.setText("martha@gmail.com");

        user3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user3.setText("martha@gmail.com");

        user4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user4.setText("martha@gmail.com");

        user5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        user5.setText("martha@gmail.com");

        time2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        time2.setText("24-12-12 17:53");

        time3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        time3.setText("24-12-12 17:53");

        time4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        time4.setText("24-12-12 17:53");

        time5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        time5.setText("24-12-12 17:53");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("Last Login");

        javax.swing.GroupLayout statSystemusageLayout = new javax.swing.GroupLayout(statSystemusage);
        statSystemusage.setLayout(statSystemusageLayout);
        statSystemusageLayout.setHorizontalGroup(
            statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statSystemusageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statSystemusageLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(statSystemusageLayout.createSequentialGroup()
                        .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addGroup(statSystemusageLayout.createSequentialGroup()
                                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(user3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(user4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(user5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(statSystemusageLayout.createSequentialGroup()
                        .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(statSystemusageLayout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        statSystemusageLayout.setVerticalGroup(
            statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statSystemusageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user1)
                    .addComponent(time1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time2)
                    .addComponent(user2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time3)
                    .addComponent(user3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time4)
                    .addComponent(user4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statSystemusageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(time5)
                    .addComponent(user5))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        statUsers1.setBackground(new java.awt.Color(255, 255, 255));
        statUsers1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel26.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel26.setText("Users");

        users_count1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        users_count1.setText("0");

        javax.swing.GroupLayout statUsers1Layout = new javax.swing.GroupLayout(statUsers1);
        statUsers1.setLayout(statUsers1Layout);
        statUsers1Layout.setHorizontalGroup(
            statUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statUsers1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(users_count1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        statUsers1Layout.setVerticalGroup(
            statUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statUsers1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(users_count1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel27.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel27.setText("Top Institutions by Assets");

        i1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        i1.setText("jLabel28");

        v1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        v1.setText("jLabel28");

        i2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        i2.setText("jLabel28");

        i4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        i4.setText("jLabel28");

        i5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        i5.setText("jLabel28");

        v5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        v5.setText("jLabel28");

        v3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        v3.setText("jLabel28");

        v2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        v2.setText("jLabel28");

        i3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        i3.setText("jLabel28");

        v4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        v4.setText("jLabel28");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(i3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(i2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(i4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(i5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(v2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v3)
                            .addComponent(v4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(i1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(v1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i1)
                    .addComponent(v1))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(v2)
                    .addComponent(i2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i3)
                    .addComponent(v3))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i4)
                    .addComponent(v4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(i5)
                    .addComponent(v5))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashStatisticsLayout = new javax.swing.GroupLayout(dashStatistics);
        dashStatistics.setLayout(dashStatisticsLayout);
        dashStatisticsLayout.setHorizontalGroup(
            dashStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashStatisticsLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(dashStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dashStatisticsLayout.createSequentialGroup()
                        .addComponent(statSystemusage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashStatisticsLayout.createSequentialGroup()
                        .addComponent(statInstututions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(statUsers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(statUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        dashStatisticsLayout.setVerticalGroup(
            dashStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashStatisticsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(dashStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statUsers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statInstututions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 31, Short.MAX_VALUE)
                .addGroup(dashStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statSystemusage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        dashboardContainer.add(dashStatistics, "card2");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setText("Reports");

        statSystemusage1.setBackground(new java.awt.Color(255, 255, 255));
        statSystemusage1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel23.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel23.setText("Assets By Institutions");

        javax.swing.GroupLayout barchart_panelLayout = new javax.swing.GroupLayout(barchart_panel);
        barchart_panel.setLayout(barchart_panelLayout);
        barchart_panelLayout.setHorizontalGroup(
            barchart_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barchart_panelLayout.setVerticalGroup(
            barchart_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout statSystemusage1Layout = new javax.swing.GroupLayout(statSystemusage1);
        statSystemusage1.setLayout(statSystemusage1Layout);
        statSystemusage1Layout.setHorizontalGroup(
            statSystemusage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statSystemusage1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statSystemusage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barchart_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(statSystemusage1Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 225, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statSystemusage1Layout.setVerticalGroup(
            statSystemusage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statSystemusage1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barchart_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        statSystemusage2.setBackground(new java.awt.Color(255, 255, 255));
        statSystemusage2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel24.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel24.setText("Users By Institutions");

        javax.swing.GroupLayout chart2Layout = new javax.swing.GroupLayout(chart2);
        chart2.setLayout(chart2Layout);
        chart2Layout.setHorizontalGroup(
            chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        chart2Layout.setVerticalGroup(
            chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout statSystemusage2Layout = new javax.swing.GroupLayout(statSystemusage2);
        statSystemusage2.setLayout(statSystemusage2Layout);
        statSystemusage2Layout.setHorizontalGroup(
            statSystemusage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statSystemusage2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statSystemusage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(statSystemusage2Layout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 225, Short.MAX_VALUE)))
                .addContainerGap())
        );
        statSystemusage2Layout.setVerticalGroup(
            statSystemusage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statSystemusage2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout statReportChartLayout = new javax.swing.GroupLayout(statReportChart);
        statReportChart.setLayout(statReportChartLayout);
        statReportChartLayout.setHorizontalGroup(
            statReportChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        statReportChartLayout.setVerticalGroup(
            statReportChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dashReportsLayout = new javax.swing.GroupLayout(dashReports);
        dashReports.setLayout(dashReportsLayout);
        dashReportsLayout.setHorizontalGroup(
            dashReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dashReportsLayout.createSequentialGroup()
                        .addComponent(statSystemusage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(statSystemusage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statReportChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        dashReportsLayout.setVerticalGroup(
            dashReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashReportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statSystemusage2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dashReportsLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(statSystemusage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statReportChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        dashboardContainer.add(dashReports, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(dashboardContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_btnActionPerformed
        setDashboardPanel();
    }//GEN-LAST:event_dashboard_btnActionPerformed

    private void institution_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institution_btnActionPerformed
        setInstitutionPanel();
    }//GEN-LAST:event_institution_btnActionPerformed

    private void users_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_users_btnActionPerformed
      // TODO add your handling code here:
      setUsersPanel();
    }//GEN-LAST:event_users_btnActionPerformed

    private void reports_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reports_btnActionPerformed
        setReportsPanel();
    }//GEN-LAST:event_reports_btnActionPerformed

    private void institution_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_institution_save_btnActionPerformed
        String name=inst_name.getText();
        String location=inst_location.getText();
        String email=inst_email.getText();
        String address=inst_address.getText();
        String phone=inst_phone.getText();
        String description=inst_description.getText();
        
        //creating institution instance and saving institution
        Institution inst=new Institution();
        inst.setName(name);
        inst.setAddress(address);
        inst.setLocation(location);
        inst.setPhone(phone);
        inst.setDescription(description);
        inst.setEmail(email);
        
        boolean result=this.user.addInstitution(inst);
        if(result){
            JOptionPane.showMessageDialog(this,
                        "Data added successfully",
                        "Success Message",JOptionPane.INFORMATION_MESSAGE);
//            setInstitutionsTable();
        }else{
            JOptionPane.showMessageDialog(this,
                        "Data not added",
                        "Error",JOptionPane.ERROR_MESSAGE);
        }
        inst_name.setText("");       
        inst_description.setText("");
        inst_phone.setText("");
        inst_email.setText("");
        inst_location.setText("");
        inst_address.setText("");

    }//GEN-LAST:event_institution_save_btnActionPerformed

    private void inst_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inst_tableMousePressed
        DefaultTableModel model=(DefaultTableModel) inst_table.getModel();
        
        Institution instt=new Institution();
        instt.setId(Integer.parseInt(model.getValueAt(inst_table.getSelectedRow(),0).toString()));
        instt.setName(model.getValueAt(inst_table.getSelectedRow(), 1).toString());        
        instt.setLocation(model.getValueAt(inst_table.getSelectedRow(), 2).toString());
        instt.setAddress(model.getValueAt(inst_table.getSelectedRow(), 3).toString());
        instt.setEmail(model.getValueAt(inst_table.getSelectedRow(), 4).toString());
        instt.setPhone(model.getValueAt(inst_table.getSelectedRow(), 5).toString());
        instt.setDescription(model.getValueAt(inst_table.getSelectedRow(), 6).toString());
        instt.setState(model.getValueAt(inst_table.getSelectedRow(), 7).toString());
        
        UpdateInstitutions update=new UpdateInstitutions(this,instt);
       

    }//GEN-LAST:event_inst_tableMousePressed

    private void setInstitutions(){
        ArrayList<Institution> insts=user.getInstitutions();
        if(insts==null){
            System.out.println("Error");
        }else{
            DefaultComboBoxModel <ComboBoxItem>model=new DefaultComboBoxModel<>();
            for(Institution institution: insts){
                model.addElement(new ComboBoxItem(institution.getId(),institution.getName()));
            }
            user_institution.setModel(model);
        }
    } 
    private void setUserCountLabel(){
        int count=user.getUsersCount();
        if(count<0){
            System.out.println("Error");
        }else{
            users_count1.setText(Integer.toString(count));
        }
    }
    private void setInstitutionCountLabel(){
        int count=user.getInstitutionCount();
        if(count<0){
            System.out.println("Error");
        }else{
            inst_count.setText(Integer.toString(count));
        }
    }
    private void setReducedBalanceCount(){
        int count=user.reducedBalanceCount();
        if(count<0){
            System.out.println("Error");
        }else{
            sm_count.setText(Integer.toString(count));
        }
    }
    private void user_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_save_btnActionPerformed
        String fname=user_fname.getText();        
        String lname=user_sname.getText();
        String email=user_email.getText();
        String password=new String(user_password_field.getPassword());
        String role=(String) user_role.getSelectedItem();
        
       //getting selected institution
       ComboBoxItem item=(ComboBoxItem) user_institution.getSelectedItem();
       Institution institution=new Institution();
       institution.setId(item.getId());
       institution.setName(item.getName());
       
       User user=new User();// creating user object and assigneing details from the form
       user.setFname(fname);
       user.setLname(lname);
       user.setEmail(email);
       String hash=BCrypt.withDefaults().hashToString(12,password.toCharArray());
       user.setPassword(hash);
       user.setRole(role);
       user.setInstitution(institution);
       
       boolean result=this.user.addUser(user);
       if(result){
           JOptionPane.showMessageDialog(this,"User has been added successfully","Success", JOptionPane.INFORMATION_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(this,"Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
       }
       user_sname.setText("");
       user_password_field.setText("");
       user_email.setText("");
       user_fname.setText("");
    }//GEN-LAST:event_user_save_btnActionPerformed

    private void users_tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_users_tableMousePressed
        DefaultTableModel model=(DefaultTableModel) users_table.getModel();
        User user=new User();
        user.setId(Integer.parseInt(model.getValueAt(users_table.getSelectedRow(),0).toString()));
        user.setFname(model.getValueAt(users_table.getSelectedRow(),1).toString());
        user.setLname(model.getValueAt(users_table.getSelectedRow(),2).toString());
        user.setEmail(model.getValueAt(users_table.getSelectedRow(),3).toString());
        user.setRole(model.getValueAt(users_table.getSelectedRow(),4).toString());
        Institution inst=new Institution();
        inst.setName(model.getValueAt(users_table.getSelectedRow(),5).toString());
        user.setState(model.getValueAt(users_table.getSelectedRow(),6).toString());
        
        UpdateUsers update=new UpdateUsers(this,user);
        
    }//GEN-LAST:event_users_tableMousePressed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_logout_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel all_institutions;
    private javax.swing.JPanel all_users;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel barchart_panel;
    private javax.swing.JPanel chart2;
    private javax.swing.JPanel dashInstitutions;
    private javax.swing.JPanel dashReports;
    private javax.swing.JPanel dashStatistics;
    private javax.swing.JPanel dashUsers;
    private javax.swing.JPanel dashboardContainer;
    private javax.swing.JButton dashboard_btn;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel i3;
    private javax.swing.JLabel i4;
    private javax.swing.JLabel i5;
    private javax.swing.JTextField inst_address;
    private javax.swing.JLabel inst_count;
    private javax.swing.JTextArea inst_description;
    private javax.swing.JTextField inst_email;
    private javax.swing.JTextField inst_location;
    private javax.swing.JTextField inst_name;
    private javax.swing.JTextField inst_phone;
    private javax.swing.JTable inst_table;
    private javax.swing.JButton institution_btn;
    private javax.swing.JButton institution_save_btn;
    private javax.swing.JTabbedPane instutionsPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JPanel new_institutions;
    private javax.swing.JPanel new_user;
    private javax.swing.JButton reports_btn;
    private javax.swing.JLabel sm_count;
    private javax.swing.JPanel statInstututions;
    private javax.swing.JPanel statReportChart;
    private javax.swing.JPanel statSystemusage;
    private javax.swing.JPanel statSystemusage1;
    private javax.swing.JPanel statSystemusage2;
    private javax.swing.JPanel statUsers;
    private javax.swing.JPanel statUsers1;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    private javax.swing.JTextField user_email;
    private javax.swing.JTextField user_fname;
    private javax.swing.JComboBox user_institution;
    private javax.swing.JPasswordField user_password_field;
    private javax.swing.JComboBox<String> user_role;
    private javax.swing.JButton user_save_btn;
    private javax.swing.JTextField user_sname;
    private javax.swing.JButton users_btn;
    private javax.swing.JLabel users_count1;
    private javax.swing.JTable users_table;
    private javax.swing.JLabel v1;
    private javax.swing.JLabel v2;
    private javax.swing.JLabel v3;
    private javax.swing.JLabel v4;
    private javax.swing.JLabel v5;
    // End of variables declaration//GEN-END:variables
}
